### ISSUE TITLE
The topic numbers is a question

### ISSUE THREAD

**Issue by allenXu317** [balikasg/topicModelling#2]
how do you get this k value？

**Comment by balikasg** [comment]
There is no standard/best way. Topic models are unsupervised models. So usually, you either chain them with a downstream application trying to optimize an eval measure (think topic models are preprocessing for classification for example where you try to optimize for accuracy). Or, you may have some domain knowledge saying that a corpus of documents discusses K themes. Last, you may have something you are trying to achieve in the context of your application, so you define your own criteria of success. There are some other approaches, like applying the elbow method wrt perplexity but I am not sure how well they correlate with human evaluation.

**Comment by balikasg** [comment]
I am closing the issue, this is a question perhaps for [Data Science Stack Exchange](https://datascience.stackexchange.com/).
